### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-ElisabetRD#1]
[Sintesis- Gestión de la Calidad en Proyectos de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-ElisabetRD/files/12704345/Sintesis-.Gestion.de.la.Calidad.en.Proyectos.de.Software.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
